### PR TITLE
fix ios accelerometer input bugs

### LINKED ISSUE #117: Accelerometer input does not work for the iOS client in landscape mode
When using the iOS client in landscape mode, the accelerometer input data does not work.

### PR DESCRIPTION
**Pull request by Maliac11**
Previously, rotation with the accelerometer did not work in landscape mode. 
The heading variable needed to be changed to use the device motion roll rather than the device motion pitch to have to correct behavior. This is because the axis along the y direction changes when the phone is put in landscape mode. 

I tested this by running the app on my phone and rotating it around in portrait, left landscape, and right landscape mode. I made sure to switch from one mode to the other and confirm that I still saw the desired behavior. 

Fixes #117

### CODE REVIEW

**Comment by bengreenier** [comment]
can we add a matching test (with relative ease) to verify the behavior? If so that would be ideal! 🔥 🔥 🔥

File: Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift [hunk 1]
```diff
@@ -169,18 +171,35 @@ class VideoStreamViewController: UIViewController {
...
             return
         }
+
         prevNavHeading = navHeading
         prevNavPitch = navPitch
-        navHeading = prevNavHeading - dheading
-        navPitch = prevNavPitch + dpitch
+
+        if UIDevice.current.orientation == .landscapeLeft {
+            print("left")
```
Comment (bengreenier) [inline Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift]: nit: can we remove these prints, seems like the rest of the nearby deviceMotion code doesn't log any info, and if we're confident this works i think we can avoid these statements 🥇

File: Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift [hunk 2]
```diff
@@ -169,18 +171,35 @@ class VideoStreamViewController: UIViewController {
...
+            navPitch = prevNavPitch - droll
+            navHeading = prevNavHeading - dheading
+        } else if UIDevice.current.orientation == .landscapeRight {
+            navPitch = prevNavPitch + droll
+            navHeading = prevNavHeading - dheading
+            print("right")
```
Comment (bengreenier) [inline Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift]: nit: can we remove these prints, seems like the rest of the nearby deviceMotion code doesn't log any info, and if we're confident this works i think we can avoid these statements 🥇

File: Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift [hunk 3]
```diff
@@ -169,18 +171,35 @@ class VideoStreamViewController: UIViewController {
...
+        } else {
+            navPitch = prevNavPitch + dpitch
+            navHeading = prevNavHeading - dheading
+            print("else")
```
Comment (bengreenier) [inline Samples/Client/SwiftClient/SwiftClient/VideoStreamViewController.swift]: nit: can we remove these prints, seems like the rest of the nearby deviceMotion code doesn't log any info, and if we're confident this works i think we can avoid these statements 🥇

**Comment by bengreenier** [comment]
@michaelperel @Maliac11 if i understand correctly this also now fixes #119 ?

**Comment by bengreenier** [comment]
per convo with @Maliac11 we're going to merge this without these ui tests at this point, as we believe the cost of authoring them is much greater than the value they'll provide. as such, merging.
